  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: bash -c "
             python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      ports:
        - "8000:0.0.0.0:8000"
      depends_on:
        - db
    nginx:
      restart: always
      build: ./nginx/
      ports:
        - "80:80"
      volumes:
        - web-static:/www/static
      links:
        - web:web