  version: '3'
    
  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    web:
      build: .
      command: bash -c "python manage.py waitfordb &&
             python manage.py makemigrations core --noinput &&
             python manage.py migrate --noinput &&
             python manage.py init_project &&
             python manage.py runserver 0.0.0.0:8000"
      volumes:
        - .:/code
      ports:
        - "80:8000"
      depends_on:
        - db